### ISSUE TITLE
where is user going after return?

### ISSUE THREAD

**Issue by jitendersaini** [supercharge/promise-pool#21]
Hello,
```
const { results, errors } = await PromisePool
  .withConcurrency(2)
  .for(users)
  .process(async data => {
    const user = await User.createIfNotExisting(data)

    return user
  })
```

Please suggest what do I do with the user that is return from the above ? where to catch this? for me if I'm printing results its coming undefined? Can you please post a good example over here.

Thanks
Jitender

**Comment by marcuspoehls** [comment]
@jitendersaini Hey Jitender, the values returned by the `.process()` method are collected in the `results` property. If your process function doesn't return an item, the results stay empty. If your process function throws an error, it's collected and available in the `errors` property.

Can you please check the errors?

**Comment by marcuspoehls** [comment]
Closing this here. Please feel free to reopen this issue or create a new one if you need more information 👍
