### ISSUE TITLE
PromisePool doesn't limit parallel requests after an error occurrence

### ISSUE THREAD

**Issue by richard-lopes-ifood** [supercharge/promise-pool#23]
### Code

```
await PromisePool.for(hugeMessageArray)
  .withConcurrency(5)
  .process(async (message) => {          
    // mutate does a network operation which eventually fails
    await mutate(message);
  });
```

### Expected
Even when a async operation fails, the number of max parallel executions (5) must be respected.

### Observed
![Peek 2020-11-02 21-02](https://user-images.githubusercontent.com/51718857/97932486-e6193b80-1d4e-11eb-8748-b6a6a41575b4.gif)

Observe how the `bulk` request respect the concurrency at first, but then, when the first error occurrs, it calls `process` without respecting the concurrency limit.

**Comment by marcuspoehls** [comment]
@richard-lopes-ifood Hey Richard, thank you for the details and gif. These are the details I need to create a failing test making sure we can fix the issue. I'll look into this today.

**Comment by marcuspoehls** [comment]
@richard-lopes-ifood I found and fixed the issue: a failed task wasn’t removed from the list of active tasks. That’s why they always won the `Promise.race` for the text task to finish. The failed task then failed again and wasn’t removed but created the next free slot. Overall, the pool finished but started all tasks after the first failed task.

Very good catch, thank you for reporting this!

I’m going to prepare the next release and publish it to NPM soon

**Comment by marcuspoehls** [comment]
Version `1.6.0` is published on NPM 👍
