### ISSUE TITLE
Canceling a pool

### ISSUE THREAD

**Issue by Christilut** [supercharge/promise-pool#24]
I'm running a pool that takes a while, is there any way to cancel it?

I guess I can do a workaround like this:
```ts
.process(async data => {
  if (canceled) return

})
```

But that would still iterate all input elements for nothing.

**Comment by marcuspoehls** [comment]
@Christilut Hey Christiaan, cancelling a pool is possible with a bit of manual work.

At this point, there’s no method allowing you to manually stop the pool. What you can do as a workaround is throwing a custom error, like `CancelPoolError`. You must throw this error from  the `pool.process()` method. Then, you must rethrow the error within a custom error handler. Thrown errors inside of the `pool.handleError` method will be passed through to your application.

Here’s a sample setup that may work for you:

```js
try {
  const errors = []

  const { results } = await PromisePool
    .for(users)
    .handleError(async (error, user) => {
      if (error instanceof CancelPoolError) {
        throw error // Uncaught errors will stop the promise pool
      }

      errors.push(error) // you must collect errors yourself
    })
    .process(async data => {
      if (canceled) {
        throw new CancelPoolError()
      }
      
      // your processing
    })

  await handleCollected(errors) // this may throw

  return { results }
} catch (error) {
  // this should only be reached when the CancelPoolError was thrown
}
```

I’m happy to review and support you with a pull request. I won’t have time to implement a `pool.cancel()` method this year. I will be able to work on the cancelling feature in the beginning of 2021

**Comment by Christilut** [comment]
Thanks for the super quick response :)

I'll use your workaround for now, it does the trick nicely.

**Comment by marcuspoehls** [comment]
Sweet!

I'll close this issue and open a new one for the "stopping the pool" feature.

**Comment by Christilut** [comment]
Awesome! Appreciate the quick and helpful response :)

**Comment by marcuspoehls** [comment]
@Christilut You’re welcome! :)
