### ISSUE TITLE
Allow the pool to "failLoud" on error

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/promise-pool#3]
Currently, the promise pool run the given callback on each item. Even though an error happens during the processing. The pool won't fail on errors and instead collect all errors.

This PR should add an option to let the pool fail loud instead of being silent on errors.

**Expected API**

```js
try {
  const pool = new PromisePool()
    .for(users)
    .failLoud()  // <-- new method

  await pool.process(async user => {
    // process user
  })
} catch (error) {
  // handle error 
}
```

**Comment by Fly-Style** [comment]
I'd like to pick this issue.

**Comment by marcuspoehls** [comment]
@Fly-Style Sure! Thank you

**Comment by Fly-Style** [comment]
@marcuspoehls FYI : I am working on another PR now. But when I will end it, work on this issue will be started.

**Comment by marcuspoehls** [comment]
@Fly-Style Hey Alex, thank you for the update :+1:

**Comment by marcuspoehls** [comment]
@Fly-Style Hi Alex, can I help you with the task? Anything I should describe or explain in more detail? Just let me know if you want help, I'm happy to help

**Comment by Fly-Style** [comment]
@marcuspoehls hi, Marcus. I will start it today. 
Could you please describe method behaviour in more detail? :)

**Comment by marcuspoehls** [comment]
@marcuspoehls Nice!

My idea was to add a `.failLoud()` method that configures the promise-pool the throw an error as soon as it occurs. At this point, the library collects all errors and processes every item.

In the last days, I was thinking through this approach and decided to change direction. I'd like to introduce a breaking change and throw errors instead of collecting them. 

If you're still interested in implementing the changes, here's what the `promise-pool` library should do in the future:

- throw on error: no try/catch to collect errors
- return the `results` directory, not wrapped in an object

Does this make sense?
Are you still on board implementing the changes and submitting a PR for it?

**Comment by Fly-Style** [comment]
@marcuspoehls I am still on board; I had big release on my current job this week. 
I start to implement it.

**Comment by marcuspoehls** [comment]
@Fly-Style Great, thank you!

**Comment by marcuspoehls** [comment]
@Fly-Style Hey Alex, can you please share your status? Can I help you with this feature? Should I share more specific ideas for the implementation?

Just wanted to reach out in case you need help

**Comment by txau** [comment]
@marcuspoehls @Fly-Style It would be great if the behavior regarding exceptions could be controlled externally. In my particular use case I'd like to only halt the whole process depending on the type of error.

**Comment by marcuspoehls** [comment]
@txau Hey Jaume, thank you for your feedback. I like the idea of an improved error handling using conditional catching/throwing. I’ll think about this over the weekend.

@txau I have a question related to your promise pool usage: do you handle errors in case they appear or do you ignore them at this point?

**Comment by txau** [comment]
@marcuspoehls we are using promise-pool to bulk index entities in elastic search in this project: https://github.com/huridocs/uwazi

Before implementing promise-pool, we were collecting the non-critical exceptions and reporting at the end of the reindex. For critical errors, we would halt the process and report immediately. Now with promise-pool we just collect the errors and report them at the end.

I hope this helps!

**Comment by marcuspoehls** [comment]
@txau yep, very helpful! Thank you

**Comment by marcuspoehls** [comment]
@txau Hey Jaume, I’m planning a new major release of the promise pool library changing the default behavior of collecting all errors to throwing immediately on error. As a user of the package, you’re able to intercept the error handling.

Here’s how the new functionality may look like (depending on your feedback 😃 )

```js
const PromisePool = require('@supercharge/promise-pool')

const results = await PromisePool
  .for(items)
  .withConcurrency(3)
  .onError((error, item) => {
    if (error instanceof SystemError) {
      return
    }
    
    throw error
  })
  .process(item => {
    // ... item processing
  })
```

What do you think about the `onError` callback to customize the error handling?
The `onError` callback will be called for each item throwing an error in the `process` callback.

At this point, there’s no support for an async error handler.
Would an async error handler useful? I mean `.onError(async (error, item) => {})`

**Comment by RafaPolit** [comment]
@marcuspoehls thanks for this effort and tool.  I'm working with @txau on the Uwazi project, so I'd thought I'd chime in with some questions.

Would this onError hook, upon `return` (instead of throw), allow the process to continue where it stopped?

Let me elaborate on our scenario, to see if this brings any light.  Lets say we want to run 3 batches or 3 documents to get indexed in ElasticSearch.

Scenario 1: All goes well, nothing to report, no errors, all good, move along!

Scenario 2: Batch 2 contains a problematic 2nd item.  We would ideally want to index all batch 1, all batch 3, and 2 out of 3 documents of problematic batch 2.  If you 'stop on error', we would get unknown number of correctly processed items in batch 2, forcing to repeat the entire process.

Ideally, this scenario should work as your current implementation, just cycling through all the batches and reporting any errors it finds.

Scenario 3: there is no response from the server.  Of course, here, you don't want to move through all the batches, you want to exit on error, right away.

If the `onError`'s return will allow scenario 2, then yes, that would be great.  But it doesn't seem like it.  Am I reading this wrong?

Thanks again.

**Comment by RafaPolit** [comment]
Regarding async: as of now, I think we could do without it, but I don't see some scenarios where it would be interesting.  Perhaps there is little impact in terms of performance to implement it with async from the start?  Not sure.

**Comment by marcuspoehls** [comment]
@RafaPolit Hey Rafael, thank you for your extensive descriptions and questions. Good points!

- **Question:** Would this onError hook, upon return (instead of throw), allow the process to continue where it stopped?
- **Answer:** Yes. The `onError` hook is a way to handle error “in your way”. In the current `1.x` release line, the library collects all errors while processing the items. You need to handle errors at the end when all items have been processed. I’m planning to change the error handling in the new release line `2.x`. The idea for `2.x` is to `throw` and stop processing as soon as an error occurs. A way to **continue** processing the remaining items in the pool is a custom `onError` hook that does not throw. The provided callback to `onError` is used as the `catch` part in the `try/catch` handling when processing an item.

- **Q:** Will the `onError` hook allow scenario?
- **A:** Yes. The difference here, you must collect errors yourself.

---

**Planned Breaking Changes**
The release I’m currently planning would not collect errors anymore. It would directly return the results. When an error happens, the default behavior is to throw the error (behaving more in line with Array-like methods). I’m thinking of the `onError` hook to still allow error handling on the user side. Let’s have a look at some examples 😃 

**Before (currently available release line `1.x`)**

```js
const PromisePool = require('@supercharge/promise-pool')

const { results, errors } = await PromisePool
  .for(documents)
  .withConcurrency(3)
  .process(async document => {
    await Elastic.saveAndIndex(document)
  })
```

You can handle any error at the end, for example enqueuing failed documents for reindexing. 

**After (planned release line `2.x`)**

```js
const PromisePool = require('@supercharge/promise-pool')
const errors = []

const results = await PromisePool
  .for(documents)
  .withConcurrency(3)
  .onError(async (error, document) {
    if (error instanceof ElasticIndexingError) {
      // returning without throwing the error proceeds the promise pool processing from where it stopped for the remaining documents
      return errors.push({ error, document })

      // or
      return Elastic.enqueueForReindexing(document)
    }

    // re-throwing the error stops processing and exits the pool
    throw error
  })
  .process(async document => {
    await Elastic.saveAndIndex(document)
  })
```

While writing the proposed handling for v2 I’m noticing you probably have an extra error handling part at the end. The differences are that you can now stop early and intercept the error handling with the downside of moving the error handling via an `errors` to your side.

@RafaPolit Seeing the code snippet, is the `onError` hook helpful for you?

**Comment by marcuspoehls** [comment]
@txau @RafaPolit I was thinking through the proposed `onError` hook over the last hours. I feel like it’s not there yet. There’s something missing. I actually like the collected errors being in the package. Handing over the error collecting process to the package user feels wrong. I’m referencing the "v2" code snippet from the comment above.

Another idea I was debating is the original `failLoud()` method. The intention with `failLoud()` is to throw an error as soon as it occurs. When failing loud, processing stops on an error and the remaining items in the pool won’t be processed. The failing item would then be part of the error to have a chance figuring out which document caused the issue and also which documents in the collection were already processed.

A more detailed version of failing loud can be `failLoudOn(ErrorClass)` where `ErrorClass` can be any JavaScript error class. This would allow a full stop on specific errors, like `ElasticConnectionError`. This approach assumes users are creating and using custom error classes.

The naming can vary though. My ideas are `failLoudOn(...)` or `throwOn(...)`.

What do you think about the `failLoud()` or `failLoudOn()` methods?

**Comment by SimonJang** [comment]
Any update on this issue?

I am mainly using [p-map](https://github.com/sindresorhus/p-map) and [p-settle](https://github.com/sindresorhus/p-settle) at the moment but I like the idea that you can have some kind of error handling while looping and the fluent style of promise-pool.

If you don't have time, I can pickup the issue if you want.

**Comment by marcuspoehls** [comment]
@SimonJang Hey Simon, I didn't work on this feature over the last couple of weeks.

I'd like to settle on the handling a bit more than my loose thoughts from above 😃

Simon, how would you imagine or like to intercept errors/error handling in the promise pool?

**Comment by SimonJang** [comment]
Hey @marcuspoehls, thanks for the quick response!

Preferably, I would like to handle the separate errors, like you suggested above:

```javascript
const results = await PromisePool
  .for(documents)
  .withConcurrency(3)
  .onError(async (error, document) {
    // custom error handling
  }
```

This makes it easier to rollback changes, implement custom retry logic, notifying clients on errors, etc. I honestly think that in most cases, you would like some kind of error handling.

Does failing 'loud' mean, that the loop is aborted if you encounter an error and throw that error? Or does it throw an error if there is any error, after completing the loop?

**Comment by marcuspoehls** [comment]
@SimonJang Hey Simon, I agree: at some point most of the promise pool users want some kind of dedicated error handling for their app.

I’m currently thinking through the error handling cases. I’ll share my an overview of my thoughts tomorrow. We can then iterate over all ideas

**Comment by marcuspoehls** [comment]
Here are my thoughts on this feature. They deviate in a sense from the original idea to simply `failLoud`.

## 1. Throw error as soon as it occurs
The idea is to add a `.throwErrors()` method to the promise-pool allowing you to configure the pool to throw errors instead of collecting them. This would align with the current default Node.js error handling. In codebases using async/await it’s common to let errors propagate up the chain and handle them when needed.

A noticeable change would be that the promise-pool doesn’t return the successfully processed items. The successfully processed items are only returned if the poll doesn’t throw. Users would need to handle the error and possibly start processing all items again in case of an error. The item causing the error will be available at `error.item`.

**Usage example**

```js
const PromisePool = require('@supercharge/promise-pool')

try {
  const { results } = await PromisePool
    .for(users)
    .throwErrors()
    .withConcurrency(4)
    .process(async user => { … })
} catch (error) {
  // handle error, like restart processing if possible
  // `error.item` to retrieve the item that caused the error
}
```


## 2. Throw only on specific errors
Here the idea is to combine collecting errors and only throw if a specific error occurs. A use case can be database connection issues where a user wants to stop processing early because each item would fail due to the missing database connection. Errors that don’t match the provided error class are collected and returned when all items are processed.

**Usage example**

```js
const PromisePool = require('@supercharge/promise-pool')
const DatabaseConnectionError = require('../errors/database-connection-error')

try {
  const { results, errors } = await PromisePool
    .for(users)
    .withConcurrency(4)
    .throwOn(DatabaseConnectionError)
    .process(async user => { … })
} catch (databaseConnectionError) {
  // handle error, like restart processing if possible
  // `error.item` to retrieve the item that caused the error
}
```


## 3. Support an onError Hook
Instead of directly throwing errors, another idea is an `.onError((error, item) => { … })` hook. This `onError` hook accepts a callback receiving a promise-pool error instance as the first parameter and the item causing this error as the second item. The `error` parameter in the onError callback could also contain the item in the `error.item` property keeping consistency with the available error handling options.

When throwing an error or rethrowing the existing error from within the `onError` hook, the pool stops processing. In such a case, the pool won’t return any results and instead halt processing, clean up, and then rethrow a possibly thrown error from within the `onError` hook. Any returned value from the `onError` hook will be ignored.

**Usage example**

```js
const PromisePool = require('@supercharge/promise-pool')
const ElasticIndexingError = require('../errors/elastic-indexing-error')

try {
  const { results, errors } = await PromisePool
    .for(users)
    .withConcurrency(4)
    .onError(async (error, user) {
      if (error instanceof ElasticIndexingError) {
        // throwing the error from inside the onError hook stops processing and exits the pool
        throw error
      }

      // any returned value will be ignored
      return 123
    })
    .process(async user => { … })
} catch (elasticIndexingError) {
  // handle error, like restart processing if possible
  // `error.item` to retrieve the item that caused the error
}
```


---

@SimonJang @RafaPolit @txau 
I’m currently leaning towards this approach because it gives users the most flexibility in terms of error handling.

- What do you think of the three proposals?
- Which one is your favorite?

I’m happy about your feedback and suggestions. Thank you!

**Comment by SimonJang** [comment]
@marcuspoehls Nice to have this discussion going, it was food for thought. These are my thought on your suggestions.

> ### 1. Throw error as soon as it occurs
> 
> A noticeable change would be that the promise-pool doesn’t return the successfully processed items. The successfully processed items are only returned if the poll doesn’t throw. Users would need to handle the error and possibly start processing all items again in case of an error. The item causing the error will be available at `error.item`.

I think this would be a nice addition to the `promise-pool` as it mimics NodeJS default error propagation.

> ### 2. Throw only on specific errors
> Here the idea is to combine collecting errors and only throw if a specific error occurs. A use case can be database connection issues where a user wants to stop processing early because each item would fail due to the missing database connection. Errors that don’t match the provided error class are collected and returned when all items are processed.

I think this will result in a confusing API (I find it confusing :sweat_smile:). As you have both the errors collected (which might require the same error handling like the `catch` clause) and you have to do some custom error handling as well in the catch clause.

> 
> ### 3. Support an onError Hook
> Instead of directly throwing errors, another idea is an `.onError((error, item) => { … })` hook. This `onError` hook accepts a callback receiving a promise-pool error instance as the first parameter and the item causing this error as the second item. The `error` parameter in the onError callback could also contain the item in the `error.item` property keeping consistency with the available error handling options.
> 
> Any returned value from the `onError` hook will be ignored.

The last suggestion is my preferred choice since it's the most granular and provides the most customization for error handling. Just wondering why you would ignore the value returned in the error handling? And if I am right, if you rethrow the error or throw a new error, then the flow is like `1. Throw error as soon as it occurs`?

Summary:

I would add 1 and 3 as they both provide different levels of error handling and are complementary features.

**Comment by RafaPolit** [comment]
I honestly like `#3`.  The beauty of it is that I think it allows us to achieve `#1` and `#2` without a lot of difficulty.  And even evolve it to be as complex as you need.  The other two scenarios seem a bit more constraining.  You never know what scenarios people are solving with that.

And it is simple to collect the errors from the hook.  I agree it could be nice to collect them in the package for some scenarios, but then again, someone's specific collection needs may be different, so I really like `#3`.

**Comment by marcuspoehls** [comment]
Thank you for your feedback. I appreciate you sharing your thoughts. I'm currently on vacation and back at the desk on Oct 19th.

@SimonJang Simon, are you able to prepare a pull request for idea `#3`?

I'm also open to add idea `#1` (throwing in first error instead of collecting it). Let's tackle `#1` in another iteration.

**Comment by SimonJang** [comment]
@marcuspoehls Ok, I'll have something in PR by the end of the week. Enjoy you vacation!

**Comment by marcuspoehls** [comment]
@SimonJano Thank you Simon!

**Comment by SimonJang** [comment]
@marcuspoehls PR is opened, looking forward to the feedback!

**Comment by marcuspoehls** [comment]
Version `1.6.0` containing custom error handling is published on NPM 👍 

@SimonJang Kudos to you, thank you for the implementation.
@txau @RafaPolit Thank you for sharing your thoughts and ideas.
