### ISSUE TITLE
Add example of async generator

### ISSUE THREAD

**Issue by glensc** [supercharge/promise-pool#31]
How to use this with code that uses async generator:
- https://github.com/glensc/comics-downloader/blob/0.2.2/src/Command/DownloadCommand.ts#L20

the code that is slow there are is that downloads parts:
- https://github.com/glensc/comics-downloader/blob/0.2.2/src/Command/DownloadCommand.ts#L27
- https://github.com/glensc/comics-downloader/blob/0.2.2/src/Command/DownloadCommand.ts#L43
    - https://github.com/glensc/comics-downloader/blob/0.2.2/src/Command/DownloadCommand.ts#L79

**Comment by marcuspoehls** [comment]
Hey Elan, as a heads up: I’m not using generators in my code. Yet, I have a suggestion how you may benefit from the promise pool.

I scanned your code and you’re retrieving the attachments which is an async generator function. The generator function yields an export for individual messages. What you may do is refactoring your message handling code to process messages in the promise pool. With `findMessages` you’re retrieving all messages. That can be the input for the promise pool. Then, you can handle each message inside of the `PromisePool#process` function. That would allow you to download contents for X messages in parallel. You may use a pool concurrency of 100 or more to shift the bottleneck from "download contents for a single message" to "download for 100 messages and use my internet bandwidth"

Does this help you?

**Comment by glensc** [comment]
@marcuspoehls it definitely helps to get some feedback.

that would solve half of the problem, getting feed for `getAttachments()`, but there's another point that needs to be parallelized, the actual download in `execute` needs parallelizing as well. i.e the file exists check there can skip the `getData()` call, so doing it all in `process` would be a waste (as data might now be used).

I will likely not refactor the example application, as I completed the whole download in single-threaded mode already. but you may be useful for this project as a whole to have a solution for async iterators.

actually, seems I was referring to async generators specifically, not just async iterators, and perhaps implementation details come of help:
- https://javascript.info/async-iterators-generators

**Comment by marcuspoehls** [comment]
@glensc thank you for the details. I guess you’ll then not use this library. Closing this here. Please feel free to re-open if I got you wrong
