### ISSUE TITLE
promise pool is not working for all elements

### ISSUE THREAD

**Issue by numfin** [supercharge/promise-pool#32]
Screenshot says all

![image](https://user-images.githubusercontent.com/8134947/126545832-340f4c8f-13be-468a-946f-40a3f9272f04.png)

**Comment by numfin** [comment]
https://github.com/nodejs/node/issues/22088

**Comment by numfin** [comment]
Problem was that i didnt execute function inside promise and started blaming everyone except myself. Sorry for interruption

**Comment by marcuspoehls** [comment]
No worries! It’s great you found the issue 👍
