### ISSUE TITLE
need onProgress(completedTasks)

### ISSUE THREAD

**Issue by Azrideus** [supercharge/promise-pool#33]
we need a onProgress callback to see how many promises are fulfilled, useful for making progressbars

```js
.onProgress((completedTasks)=>{
//update progressbar

})
.proccess(async (s)=>{
//...
}
);
```

**Comment by marcuspoehls** [comment]
@Azrideus Sounds good, I like the idea! Do you want to submit a pull request?

**Comment by Azrideus** [comment]
Hello I made a PR, please check it
