### ISSUE TITLE
Obtain current iteration on pool

### ISSUE THREAD

**Issue by WildEgo** [supercharge/promise-pool#35]
Hey guys!

Amazing library, just started playing with it and was wondering if there's any way to get the current iteration for said pool kinda like a foreach, example of what it'd look like below.

```
.process(async (uri: string, i: number) => {
```

It would be amazingly useful for me with what I'm doing in the backend.

Thanks in advance,
Luis Bizarro

**Comment by marcuspoehls** [comment]
Hey Luis,

thank you for reaching out! I like your idea of adding the current iteration like an index in a forEach loop.

Currently we're only passing the item to the process callback. I assume we can add the iteration index without a breaking change 😃

Do you want to submit a pull request for that feature?

**Comment by WildEgo** [comment]
> Hey Luis,
> 
> thank you for reaching out! I like your idea of adding the current iteration like an index in a forEach loop.
> 
> Currently we're only passing the item to the process callback. I assume we can add the iteration index without a breaking change 😃
> 
> Do you want to submit a pull request for that feature?

Should be done at #36 !

Thank you

**Comment by marcuspoehls** [comment]
This feature is part of release `1.8.0` and published on NPM 🤝 
Thank you Luis!
