### ISSUE TITLE
Preserving the original errors

### ISSUE THREAD

**Issue by CoffeeFlux** [supercharge/promise-pool#40]
Hi! Really appreciate your work on PromisePool.

Is there any way to preserve the original error being thrown from within the PromisePool? Right now it just gets stringified and recreated as a PromisePoolError, which strips away a lot of useful contextual information.

**Comment by marcuspoehls** [comment]
@CoffeeFlux Hey Ryan, you’re right. At this point the original error gets wrapped and all context is gone. We should improve this handling.

My idea by wrapping the original error was to also assign the item that caused the error. What do you think about extending the `PromisePoolError` class to expose an `error.raw` property containing the original error? This is in alignment with `error.item` containing the original item causing the error.

Do you have another idea?

**Comment by CoffeeFlux** [comment]
That sounds great to me - would definitely solve my use case.

2021年12月9日(木) 4:40 Marcus Poehls ***@***.***>:

**Comment by marcuspoehls** [comment]
@CoffeeFlux Would you like to submit a pull request?

**Comment by CoffeeFlux** [comment]
I'm happy to submit one if you'd prefer - I'll get something up later today.

2021年12月10日(金) 5:49 Marcus Poehls ***@***.***>:

**Comment by marcuspoehls** [comment]
Thank you!
