### ISSUE TITLE
Progress for Started and Finished Tasks

### ISSUE THREAD

**Issue by WillianAgostini** [supercharge/promise-pool#43]
Hi,

We need a callback to see how many promises are fulfilled, useful for making progress bars and see what task has finished.
Relationed to issue #33 and PR #34 that wasn't completed.

I see 2 callback:

**onTaskStarted(item, percentage, activeTasks, finishedTasks)**
* item: item has started
* percentage: progress of items that has started
* activeTasks: array of running tasks
* finishedTasks: array of completed tasks 

**onTaskFinished(item, percentage, activeTasks, finishedTasks)**
* item: item has finished
* percentage: progress of items that has finished

If you approve I can share a PR

**Comment by WillianAgostini** [comment]
Hi @marcuspoehls,

Ok, I created a PR #44.

**Comment by marcuspoehls** [comment]
@WillianAgostini Hey Willian, thank you for your patience 👍 I’m back from vacation and will look through your merge request today.

**Comment by marcuspoehls** [comment]
Hey Willian, your pull request looks good! Thank you for submitting it.

I’ll apply some minor changes myself (without asking you to provide the changes):
- allow multiple event handlers for `onTaskStarted` and `onTaskFinished`
- refine the event callbacks and probably provide a `statistics` argument. This removes a long list of arguments to a function and we can extend the statistics when needed

I’ve created a new branch `item-started-finished-events` for that and merged your pull request into that.

Everything will be documented before creating a new release 😃 Thank you again for this suggestion and providing a pull request ❤️

**Comment by marcuspoehls** [comment]
@WillianAgostini Hey Willian, thank you for your patience! I’ve published a new release to NPM. Version `2.2.0` is available including the two new `onTaskStarted` and `onTaskFinished` methods. Thank you again for your contribution!

**Comment by marcuspoehls** [comment]
I’ve added sections in the docs for both methods:

- [`onTaskStarted`](https://superchargejs.com/docs/2.x/promise-pool#run-callbacks-when-a-task-starts)
- [`onTaskFinished`](http://localhost:3000/docs/2.x/promise-pool#run-callbacks-when-a-task-finished)
