### ISSUE TITLE
Dynamically change the concurrency

### ISSUE THREAD

**Issue by sinasalek** [supercharge/promise-pool#46]
Hi,
Is it possible to change the concurrency while it's running? the usage is for warming up purpose in the cloud. So it can start with 2 and go up after each x task to the maximum rather than just jumping to max number right away

**Comment by marcuspoehls** [comment]
Hey, 

it's currently not possible to adjust the pool size of a running/exiating promise pool.

I feel like it could be possible to make the concurrency adjustable.

In your use case, are you reusing a promise pool instance during the warmings? Or do you create a new instance when running the warming?

**Comment by sinasalek** [comment]
No there is only on promise pool in my case. it is possible to add a wrapper function and start with lower number of concurrency for x number of tasks and then switch to a higher number but it won't actually be dynamic but I would be a very rigid code. Is there a callback when the promise-pools start grabbing a new task? maybe I can leverage that pause that when the number of tasks reaches certain number and then gradually increase it. there is onTaskStarted but it is after it's started

**Comment by marcuspoehls** [comment]
@sinasalek Hey Sina, I’ve added the functionality to change the concurrency for a running pool. This change is part of the `2.3.0` release.

Here’s how you use it:

```ts
import { PromisePool } from '@supercharge/promise-pool'

await PromisePool
  .for([…])
  .withConcurrency(10)
  .process((item, index, pool) => {
    if (condition) {
      pool.useConcurrency(2)
    }

    await runYourTask()
  })
```

**Comment by sinasalek** [comment]
Oh that's great thank you. I'll give it a try

**Comment by marcuspoehls** [comment]
@sinasalek Sweet! Please let me know if everything works as expected

**Comment by marcuspoehls** [comment]
Closing the ticket here as I’m assuming everything is working fine 😃
