### ISSUE TITLE
`onTaskStarted` and `onTaskFinished` out of date in README

### ISSUE THREAD

**Issue by tomfuertes** [supercharge/promise-pool#49]
Signature and params passed to `onTaskStarted` don't match types returned of code as far as I can tell. 

Currently in src `handler(item, pool)`

Readme Docs: `handler(item, percentage, finished, active)`

**Comment by marcuspoehls** [comment]
@tomfuertes Hey Tom, thank you very much for pointing this out. And also for sending along a pull request 😃 I really appreciate it!
