### ISSUE TITLE
Pool not terminating correcly

### ISSUE THREAD

**Issue by murar8** [supercharge/promise-pool#51]
First of all thank you for this great package. I noticed an issue in version 2.3.0 where if you rethrow the error in the error handler the promise chain doesn't get stopped but it gets executed to completion (this only happens when concurrency is higher than 1). Downgraded to 2.2.0 and it works perfectly. I will create a minimal reproducible example as soon as I have some free time.

**Comment by murar8** [comment]
Here you go: https://runkit.com/murar8/62ec1d2e2ece46000c646c7d

**Comment by marcuspoehls** [comment]
Found the solution and published a patch release `2.3.1` to NPM 😃 Thank you for your help detecting this Lorenzo!

**Comment by murar8** [comment]
I updated the runkit example to 2.3.1 but it looks like the issue is still present?

**Comment by marcuspoehls** [comment]
I can reproduce the issue for an async function that doesn’t await an operation … I’ll look into this.

**Comment by murar8** [comment]
Ok thanks

**Comment by marcuspoehls** [comment]
Found the issue (hopefully 🤞😄). Going to publish another patch release

**Comment by marcuspoehls** [comment]
Version `2.3.2` is now available on NPM

**Comment by murar8** [comment]
Looks like everything is fine now, thank you.
