### ISSUE TITLE
question: is this similar to async queue?

### ISSUE THREAD

**Issue by bboydflo** [supercharge/promise-pool#52]
Hey, nice lib! After I read a bit on the docs I like the api, but to me it seems like the internals could be just a wrapper around this https://caolan.github.io/async/v3/docs.html#queue? I just wanted to mention this since the above package seems like it's very well maintained, has good typescript support and is battle tested (approx 48 million weekly downloads).

Again, just wanted to give you a heads up. Feel free to close this "issue".

**Comment by marcuspoehls** [comment]
Hey Florin,

this library is similar to async’s queue, like both are processing items concurrently. While using the promise pool, you’re initializing it for a list of items and start processing immediately after using the `.process` method. The async queue requires you to set up callbacks for each situation (process, error, drained) and separately pushing items to the queue. The async queue is basically separating all steps.
