### ISSUE TITLE
Question about the pool

### ISSUE THREAD

**Issue by alacret** [supercharge/promise-pool#53]
Does the pool runs every time the max concurrency? Or does it work in batches?

For example, given 10 elements with a concurrency set of 2:

a. Does it does 5 iterations using 2 elements at the time? or
b. As soon as 1 promise gets resolved, immediately starts another until it reaches 2 active promises?

**Comment by marcuspoehls** [comment]
@alacret Hey Angel, it's B. The pool runs at max concurrency all the time. The next promise starts processing as soon as a an active promise finishes (resolves/rejects).
