### ISSUE TITLE
skip a task from including in result

### ISSUE THREAD

**Issue by Thore1954** [supercharge/promise-pool#60]
Basically I want to do filtering on my original list based on the result of async operations. I tried returning `undefined` from the `process` callback but it just fills the resulting array with `undefined`s. Is there a way to skip including a value in the resulting array like `pMapSkip` from sindresorhus/p-map#39?

**Comment by tylercollier** [comment]
Is filtering the end result of `undefined`'s not a valid solution? Or how about returning a known [`Symbol`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol). The symbol could be e.g. `Symbol('skipped')`, and then you could filter those out of the result.

@marcuspoehls can correct me if I'm wrong but I think you could just throw an error to skip it. It would of course show in the returned `errors` value.

**Comment by Thore1954** [comment]
Of course you eventually need to filter the end result or the errors. I just thought it was already built in. Closing this.
