### ISSUE TITLE
How to retry a fixed number of times a failed promise? 

### ISSUE THREAD

**Issue by HereFrank** [supercharge/promise-pool#61]
I have a promise pool like these... 
```ts
  // Creating imageLinks   
  const { results } = await PromisePool.withConcurrency(20)
  .for(metaplexFiles)
  .process(async (metaplexFile) => {
  console.log("creating an imageLink")
    
    const imageLink = await metaplex.storage().upload(metaplexFile)
    console.log('arweave link created', imageLink)
    
    return imageLink;
  })
  ```
  
Being `metaplexFile` an array of `Files[]` that when passed through the promise `metaplex.storage().upload(metaplexFile)` generates a link... 

Now...
Sometimes these process fail, and the link is not generated
And I just want **to retry at least 5 times that promises that fail** any help? 

I have read the [error handling documentation](https://superchargejs.com/docs/3.x/promise-pool#error-handling)

I understand that I can catch the error:

- At the moment with `.handleError()`
- Or at the end with `errors` 

But I'm not sure what is the correct approach... 
These is one example of my generated links: 
https://i.imgur.com/iGEdFgo.png
here I generated 8 successfully links...
But 2 cases give me an error...

I tried to collect the errors in this way at the end... 
https://i.imgur.com/zSX4JCm.png
That is to say, left all the errors and try to make some type of finally 5 times retry or something like that... 
But it's seems like I'm in the same place of where I start... 
If `errors` have 100 `items` for example I could end up facing more mistakes... 

Maybe there is not way of make something like these?

```ts
  // Creating imageLinks   
  const { results } = await PromisePool.withConcurrency(20)
  .for(metaplexFiles)
  .handleError(async (err) => {
    // MAKE SOME RETRY LOGIC HERE TO SEND THE PROMISE AGAIN TO `.process` 5 times or the max number of times that I decided??? 
  })
  .process(async (metaplexFile) => {
  console.log("creating an imageLink")
    
    const imageLink = await metaplex.storage().upload(metaplexFile)
    console.log('arweave link created', imageLink)
    
    return imageLink;
  })
  ```
  
  But I really don't know how to make these logic of retry and send again to `.process()`
  Any help with these issue?

**Comment by marcuspoehls** [comment]
@HereFrank Hey Frank, this package doesn’t come with retry logic. You must manually implement it. You could use a retry package from NPM, like this one: https://github.com/sindresorhus/p-retry

Inside the `process` function, you’re wrapping your calls that should be retried inside the retry function.

```js
  import pRetry, {AbortError} from https://github.com/sindresorhus/p-retry;

  // Creating imageLinks   
  const { results } = await PromisePool.withConcurrency(20)
  .for(metaplexFiles)
  .process(async (metaplexFile) => {
    console.log("creating an imageLink")

    return await pRetry(async () => {
      const imageLink = await metaplex.storage().upload(metaplexFile)
      console.log('arweave link created', imageLink)
    
      return imageLink;
    }, { retries: 5 })
  })
```

**Comment by HereFrank** [comment]
> @HereFrank Hey Frank, this package doesn’t come with retry logic. You must manually implement it. You could use a retry package from NPM, like this one: https://github.com/sindresorhus/p-retry
> 
> Inside the `process` function, you’re wrapping your calls that should be retried inside the retry function.
> 
> ```js
>   import pRetry, {AbortError} from https://github.com/sindresorhus/p-retry;
> 
>   // Creating imageLinks   
>   const { results } = await PromisePool.withConcurrency(20)
>   .for(metaplexFiles)
>   .process(async (metaplexFile) => {
>     console.log("creating an imageLink")
> 
>     return await pRetry(async () => {
>       const imageLink = await metaplex.storage().upload(metaplexFile)
>       console.log('arweave link created', imageLink)
>     
>       return imageLink;
>     }, { retries: 5 })
>   })
> ```

Awesome!!
Thanks!!
