### ISSUE TITLE
.withConcurrency(1) still processes multiple items in the array at once

### ISSUE THREAD

**Issue by mafiosnik777** [supercharge/promise-pool#62]
```js
async function processQueue() {
  const { errors } = await PromisePool
    .withConcurrency(1)
    .for(queue)
    .onTaskStarted(() => {
      console.log('Processing queue item');
    })
    .onTaskFinished(() => {
      console.log('Finished queue item');
    })
    .process(async (item) => {
      console.log(item);
      await Interpolation.process(item.file, item.model, item.output, item.params, item.extension, item.engine);
    })
    errors.forEach(error => {
      console.error(error);
    })
}
exportBtn.addEventListener('click', processQueue);
```

It seems that it's not possible to process items one by one. They still execute in parallel with at least 2 concurrent processes.
I guess the library was only designed for concurrency and it's not the usecase it was designed for?

Would it be possible to implement this?
I would love to use this library, as I prefer the syntax and features over other alternatives.

**Comment by marcuspoehls** [comment]
@mafiosnik777 Hey, it should be possible to process items sequentially in a promise pool using a concurrency of 1. I’ll double check the implementation to see what happens.

Something coming to my eye in your sample code is the order in which you’re chaining. That should not be an issue, but there might be an uncaught bug in the code.

I’m typically chaining with items first and then add the concurrency:

```js
PromisePool.for(items).withConcurrency(1)
```

You’re doing it the other way around (which should work totally fine):

```js
PromisePool.withConcurrency(1).for(items)
```

**Comment by marcuspoehls** [comment]
I added a test using a concurrency of 1 and the pool processes sequentially as expected https://github.com/supercharge/promise-pool/commit/cec572d7e1106f29b6096c1c1a275942de8be7f5

@mafiosnik777 It seems like you’re using this library in the frontend. Your sample code hints a click listener on a button. Is it possible you’re having more than one click listeners calling the `processQueue` method?

**Comment by mafiosnik777** [comment]
> I added a test using a concurrency of 1 and the pool processes sequentially as expected [cec572d](https://github.com/supercharge/promise-pool/commit/cec572d7e1106f29b6096c1c1a275942de8be7f5)
> 
> @mafiosnik777 It seems like you’re using this library in the frontend. Your sample code hints a click listener on a button. Is it possible you’re having more than one click listeners calling the `processQueue` method?

I just sanity checked with another library and I get the same result.

There is only one click listener on the `processQueue` method. So there seems to be something wrong with my `Interpolation.process()` function, as it probably returns a finished state, even though it is in fact still incomplete and running.

Not an issue with `promise-pool`. 
Thanks for your help!

**Comment by marcuspoehls** [comment]
You’re welcome!
