### ISSUE TITLE
pool.stop() only stops after processing 1 additional item

### ISSUE THREAD

**Issue by mafiosnik777** [supercharge/promise-pool#63]
I have a series of long running tasks that get queued up by promise-pool. When I fire `return pool.stop()` `StopThePromisePoolError();` in `promise-pool-executor.js` gets thrown but it only stops after processing 1 additional item. 

To illustrate for replication:

![illustration](https://mafiosnik.needsmental.help/EGhM14k1MC.png?key=9zkaJC4w7XY2fo)

This is a fatal flaw on longer running processes, as it should immediately stop and not after it finishes the current task + one additional one.

```js
async function processQueue() {
      const { errors } = await PromisePool
      .withConcurrency(1)
      .for(queue)
      .onTaskStarted((item) => {
        console.log('Starting queue');
        sessionStorage.setItem('currentFile', item.file);
        // fetch metadata
        Media.fetchMetadata();
        // listen for preview
        Preview.listenForPreview();
        // initialize ui for process
        Process.startProcessInterpolation();
      })
      .onTaskFinished(() => {
        console.log('Finished queue item');
      })
      .process(async (item, index, pool) => {
        console.log(item);
        exportBtn.addEventListener('click', function () {
          console.log('stopping queue');
          return pool.stop();
        })
        await Interpolation.process(item.file, item.model, item.output, item.params, item.extension, item.engine);
      })
    errors.forEach(error => {
      console.error(error);
    })
}};
```

I tried around a lot to fix this but came to no solution.

**Comment by marcuspoehls** [comment]
@mafiosnik777 Hey, thanks for reporting this! I’ll have a look at this tomorrow. I appreciate any help from your side, in case you want to submit a pull request. Something that would be nice is a failing test case which helps me to find this issue quickly. You can provide a failing test in a pull request or as a code snippet here. Thanks for your help! 😃

**Comment by mafiosnik777** [comment]
> @mafiosnik777 Hey, thanks for reporting this! I’ll have a look at this tomorrow. I appreciate any help from your side, in case you want to submit a pull request. Something that would be nice is a failing test case which helps me to find this issue quickly. You can provide a failing test in a pull request or as a code snippet here. Thanks for your help! 😃

While building a failing test case I noticed the issue only happens when **promise-pool** is running in a browser environment in the renderer process. When I just call `node test.js` in a shell with the same code it stops on 0, exactly like it should. Unfortunately this is exactly the environment i need it in.

Anyways I replicated the issue in a small sandbox you could test this in:
https://codesandbox.io/s/trusting-antonelli-8bslfd?file=/src/index.js

No worries, let me know tomorrow when you find time to check. Thanks a lot!

**Comment by mafiosnik777** [comment]
I tried around a bit further and couldn't come up with a fix. Did you already have time to check the sandbox example?

**Comment by marcuspoehls** [comment]
@mafiosnik777 Hey, I was toying with the code in your shared codesandbox. But I didn’t find the issue yet. Was also looking through the code and maybe find an issue. I somehow need to create a local browser environment to reproduce the issue on my machine which should allow me to create a test case that I can work against.

**Comment by mafiosnik777** [comment]
@marcuspoehls Are you sure you couldn't replicate on your machine with the codesandbox? I can replicate this issue on literally every machine I have. Doesn't matter if Chrome on Windows or macOS Safari.

<img width="1138" alt="Bildschirm­foto 2022-10-11 um 12 06 57" src="https://user-images.githubusercontent.com/108760201/195063000-14c3dfec-1690-4aa5-b238-de5ba0ca94fc.png">

**Comment by marcuspoehls** [comment]
@mafiosnik777 I can replicate it in the browser. The codesandbox is fine. But I can’t replicate it locally in Node.js. I want to add a test case reproducing this behavior to update/change the code.

**Comment by mafiosnik777** [comment]
@marcuspoehls Ah, my bad, i misunderstood then.

> While building a failing test case I noticed the issue only happens when **promise-pool** is running in a browser environment in the renderer process. When I just call `node test.js` in a shell with the same code it stops on 0, exactly like it should. 

Like I already said this only happens in a browser environment. I couldn't replicate it in Node.js as well. It worked as expected in a non-browser environment, which is very weird.

**Comment by marcuspoehls** [comment]
@mafiosnik777 Hey, did you find a solution for the "+1" issue? I haven’t checked it further on my side. Maybe we can get a fix into the package to make it work properly for browser usage.

**Comment by mafiosnik777** [comment]
> @mafiosnik777 Hey, did you find a solution for the "+1" issue? I haven’t checked it further on my side. Maybe we can get a fix into the package to make it work properly for browser usage.

Unfortunately, I didn't. I just stuck to using a messy workaround now.

**Comment by m93a** [comment]
I managed to reproduce the issue in Node using the following code. It is almost identical to the [codesandbox](https://codesandbox.io/s/trusting-antonelli-8bslfd?file=/src/index.js) example, except for the fact that I use shorter delays and instead of logging to the console, I write to a local variable (so that I can check it later with `expect`).

```js
test('stops on time with timed stop call', async () => {
  const timeouts = [100, 200, 300]
  let processedSecond = false

  const { results } = await PromisePool
    .withConcurrency(1)
    .for(timeouts)
    .process(async (timeout, _, pool) => {
      // simulate user stopping pool after 50ms
      pause(50).then(() => pool.stop()).catch(() => void 0)

      if (timeout === 200) {
        processedSecond = true
      }
      // simulate load
      await pause(timeout)
      return timeout
    })
  
  // should only have finished the current task
  expect(results).toEqual([100])

  // should not have started the second task
  expect(processedSecond).toEqual(false)
})
```

I added this test in PR #72, together with a fix for the bug.
