### ISSUE TITLE
Feature request: Add additional items onto already-running PromisePool instance?

### ISSUE THREAD

**Issue by willcodeforfood** [supercharge/promise-pool#65]
Not an issue per se: more a question of "is this even possible".

The exact usecase I have is recursively crawling a directory structure via a REST API. I can only query 1 folder's contents per API call, plus it's paginated. So it requires lots of slow API calls which could be run in parallel.

Right now, I pass PromisePool a list of top-level folder IDs, then it will scan each one in parallel and save the results to a file. The trouble is: scanning that top level folder yields _more_ API calls to do, since the folder structure's depth could be infinite. In other words: Only the top-level folders benefit from parallelization.

I had thought to use PromisePool on the child folders too, but the concurrency doesn't seem to be "shared" across multiple instances of PromisePool. So then the API gets angry at me for making too many calls too fast.

So it seemed logical to have a single PromisePool instance, then as new "crawl" jobs are discovered, they can simply be pushed onto the list of remaining Promises, to be resolved whenever concurrency permits.

Questions:
Does PromisePool support this kind of workflow today?
If not, would it even be possible to implement (assuming I do the legwork and submit PR)? Or does the architecture of the existing module make this sort of thing impossible/unrealistic? Or maybe this usecase is so "niche" it doesn't have a place?

Lastly, is there a better module for this kind of thing? I came upon a few promising modules, but decided on PromisePool for its simplicity (it's amazing btw!). But now I am realizing my usecase may be more complex than I originally thought.

**Comment by tylercollier** [comment]
I'll let the library author answer whether it is/could be possible.

To solve your situation now, can you use a while loop?

```js
while (items.length) {
  // you'd do promise pool stuff here, processing the items array. It would add items to items2

  items = items2;
}
```

**Comment by marcuspoehls** [comment]
@willcodeforfood Hey Eric, as you have already noticed: there’s currently no way to add additional items to an active promise pool.

I can see your use case. At this point, you would need to create a new pool instance for all (nested) directories to request their contents concurrently.

I’m open to a pull request if you want to look into it.

@tylercollier 
PS: Thank you Tyler for your quick reply! I really appreciate your answer helping Eric out!
