### ISSUE TITLE
What's different about PromisePool & Bluebird.map

### ISSUE THREAD

**Issue by bayungrh** [supercharge/promise-pool#73]
Hi,

what is the good difference between using PromisePool & Bluebird.map ?

**Comment by marcuspoehls** [comment]
@bayungrh Hey Mochammad, I’m not familiar with `Bluebird#map`. A quick look at their docs says that both tools work similarly. A promise pool won’t throw and collect errors if you want, it allows you to provide your own error handling, and it provides you events that you can use for e.g. progress bars.
