### ISSUE TITLE
`Error.captureStackTrace` fails in some environments

### ISSUE THREAD

**Issue by lostplan** [supercharge/promise-pool#74]
`Error.captureStackTrace` is used in several places in the code: https://github.com/search?q=repo%3Asupercharge%2Fpromise-pool%20capturestacktrace&type=code

However, `captureStackTrace` is non-standard and fails in some environments. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#static_methods.

For example, in Safari:

```
Error.captureStackTrace(new Error())
// => TypeError: Error.captureStackTrace is not a function. (In 'Error.captureStackTrace()', 'Error.captureStackTrace' is undefined)
```

Consider using https://www.npmjs.com/package/capture-stack-trace for compatibility 🥺

**Comment by lostplan** [comment]
I am aware that this library is intended for Node.js but it's also super useful in the browser! I would love to see it compatible with more environments.

As far as I can tell, captureStackTrace is the only dependency on v8.

**Comment by marcuspoehls** [comment]
@lostplan Thank you for reporting this issue. We could and should add a check whether the `captureStackTrace` method exists on the global Error object. If not, we're not calling it.

Can you please prepare a pull request? 🙂
