### ISSUE TITLE
adding items to the pool during processing

### ISSUE THREAD

**Issue by pachacamac** [supercharge/promise-pool#76]
Is it possible to add items to the pool during processing somehow? This would be super useful for tasks where each task potentially creates a new task.

**Comment by marcuspoehls** [comment]
@pachacamac Hey Marc, there’s currently no convenient way to add new items to a running promise pool instance. There’s a related issue with the same question and @tylercollier suggested a solution that could fit your situation: https://github.com/supercharge/promise-pool/issues/65

I appreciate your help if you want to contribute a pull request adding the functionality to add items 🙂

**Comment by pachacamac** [comment]
Hey @marcuspoehls thanks for the quick response. I had a look at the source but ended up building my own promise based task pool that uses an interval handler as a sort of scheduler so whenever there is something in the queue and the maximum concurrency is not reached yet, new tasks are started. It seems to work fine for my use-case so will likely not come back to this sorry.

**Comment by marcuspoehls** [comment]
@pachacamac Alright, great that you found a way to solve your problem 🙂
