### ISSUE TITLE
[Question] Delay between batches?

### ISSUE THREAD

**Issue by mb8z** [supercharge/promise-pool#80]
Is is possible to add a delay between batches (or is this planned)?

Thanks – great package!

**Comment by marcuspoehls** [comment]
@mb8z Hey, this package processes each item individually. As soon as the pool finishes the processing of an item, the freed-up spot will be filled with the processing of another task.

That means, you can add the delay yourself using a JavaScript `Promise`. Here‘s a sample code:

```js

const { results, errors } = await PromisePool
  .withConcurrency(2)
  .for(yourData)
  .process(async (item, index, pool) => {
    const delayInMilliseconds = 300
    await new Promise(resolve => setTimeout(resolve, delayInMilliseconds))

    // … your processing
  })
```

Does this help you?

**Comment by mb8z** [comment]
@marcuspoehls I ended up doing something like this – was just wondering if this is maybe supported with the chain method! Thank you!

**Comment by marcuspoehls** [comment]
@mb8z Great that you solved it yourself 🙂 there’s currently no method for delays in the chain. I also don’t plan to add something like this for now
