### ISSUE TITLE
Docs: add support for iterables

### ISSUE THREAD

**Issue by ZebraFlesh** [supercharge/promise-pool#81]
It looks like #72 added support for iterables and async iterables. However, there's no mention of this in the documentation. Adding it would be helpful.

**Comment by marcuspoehls** [comment]
@ZebraFlesh Hey, good catch! Are you able to create a pull request for that against the `3.x` branch in https://github.com/supercharge/docs? 🙂

**Comment by marcuspoehls** [comment]
I added the section to the docs 😃 

https://superchargejs.com/docs/3.x/promise-pool#create-a-promise-pool-from-an-async-iterable
