### ISSUE TITLE
Delete unnecessary files from dist

### ISSUE THREAD

**Issue by alexsandrbarabash** [supercharge/promise-pool#82]
Hi, I am a develop extension for azure marketplace. And I can't publishing because dist have some file with whitespace. Can you pls fix it 🙏
![image](https://github.com/supercharge/promise-pool/assets/71293081/c66e6ea2-4baa-4a2a-a643-9104a088b2af)

**Comment by marcuspoehls** [comment]
@alexsandrbarabash Hey, thanks for pointing this out 👍 I'll fix it and remove the "copy"/duplicated files

**Comment by marcuspoehls** [comment]
@alexsandrbarabash Hey Alexandr, I’ve published version `3.1.1` on npm with a clean dist directory. Please check out the new version for your Azure marketplace extension. Please report back if version `3.1.1` works for you 🙂

**Comment by alexsandrbarabash** [comment]
@marcuspoehls Everything is fine thank you
